// Service > user

export const UPDATE_USER_NAME = "UPDATE_USER_NAME";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
export const UPDATE_USER_KEYSTORE = "UPDATE_USER_KEYSTORE";
export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";
export const UPDATE_USER_AVATAR_HASH = "UPDATE_USER_AVATAR_HASH";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
